// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOHBJeoMec7ZQFBwhmMOLqCt2MY6Ej1gY',
    appId: '1:727453889717:web:ab7f559cecfd62b758bafc',
    messagingSenderId: '727453889717',
    projectId: 'sakani-project',
    authDomain: 'sakani-project.firebaseapp.com',
    databaseURL: 'https://sakani-project-default-rtdb.firebaseio.com',
    storageBucket: 'sakani-project.appspot.com',
    measurementId: 'G-P7VGHMVEPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuTmop5t6Ji12ghFSsuW91eEKrvy8R6XQ',
    appId: '1:727453889717:android:f74df2da71d6bf4158bafc',
    messagingSenderId: '727453889717',
    projectId: 'sakani-project',
    databaseURL: 'https://sakani-project-default-rtdb.firebaseio.com',
    storageBucket: 'sakani-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJnzIGx-2c5ILJdnBpcAbhDJ_CEqfrzEI',
    appId: '1:727453889717:ios:4b89039dcb44f52f58bafc',
    messagingSenderId: '727453889717',
    projectId: 'sakani-project',
    databaseURL: 'https://sakani-project-default-rtdb.firebaseio.com',
    storageBucket: 'sakani-project.appspot.com',
    androidClientId: '727453889717-1k7g7j60n5gf0ua8m8ufsboard6rsq0v.apps.googleusercontent.com',
    iosClientId: '727453889717-3bkk8uja5uvq9tb7r549t2rftri1a4pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.homep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJnzIGx-2c5ILJdnBpcAbhDJ_CEqfrzEI',
    appId: '1:727453889717:ios:97069ba399323bc258bafc',
    messagingSenderId: '727453889717',
    projectId: 'sakani-project',
    databaseURL: 'https://sakani-project-default-rtdb.firebaseio.com',
    storageBucket: 'sakani-project.appspot.com',
    androidClientId: '727453889717-1k7g7j60n5gf0ua8m8ufsboard6rsq0v.apps.googleusercontent.com',
    iosClientId: '727453889717-pim1fbhi1jobu8jb112k7phe4v2iasp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.homep.RunnerTests',
  );
}
